# Generated by Django 5.1.3 on 2024-12-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0005_alter_stanowisko_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='folder_aplikacji.team'),
        ),
    ]
