# Generated by Django 5.1.3 on 2024-12-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0006_osoba_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Klub', 'verbose_name_plural': 'Kluby'},
        ),
        migrations.AddField(
            model_name='osoba',
            name='country',
            field=models.CharField(default='', max_length=2),
        ),
    ]
