# Generated by Django 5.1.3 on 2024-12-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0007_alter_team_options_osoba_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='country',
            field=models.CharField(default='', max_length=3),
        ),
    ]
