# Generated by Django 5.1.3 on 2024-12-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0008_alter_osoba_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='wiek',
            field=models.IntegerField(default='', max_length=2),
        ),
    ]
