# Generated by Django 5.1.3 on 2024-12-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0009_osoba_wiek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='wiek',
            field=models.IntegerField(default='0', max_length=2),
        ),
    ]
