# Generated by Django 5.1.3 on 2024-12-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0010_alter_osoba_wiek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='wiek',
        ),
    ]
