# Generated by Django 5.1.3 on 2025-01-27 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0011_remove_osoba_wiek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('view_person_other_owner', 'Pozwala zobaczyć modele Osoba innych właścicieli')], 'verbose_name': 'osoba', 'verbose_name_plural': 'osoby'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'persona', 'verbose_name_plural': 'persony'},
        ),
        migrations.AlterModelOptions(
            name='stanowisko',
            options={'verbose_name': 'stanowisko', 'verbose_name_plural': 'stanowiska'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'zespół', 'verbose_name_plural': 'zespoły'},
        ),
        migrations.RemoveField(
            model_name='osoba',
            name='country',
        ),
        migrations.RemoveField(
            model_name='osoba',
            name='team',
        ),
        migrations.AddField(
            model_name='osoba',
            name='wlasciciel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='pseudonim',
            field=models.CharField(default='', max_length=80),
        ),
    ]
